name: Daily LeetCode Post

on:
  schedule:
    # run once per day at 00:05 UTC (adjust as you want)
    - cron: '5 0 * * *'
  workflow_dispatch: {} # allow manual runs

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch LeetCode daily metadata
        id: fetch
        run: |
          python scripts/fetch_daily.py --out metadata.json
          echo "METADATA_FILE=metadata.json" >> $GITHUB_ENV

      - name: Generate post markdown (uses OpenAI if configured)
        id: gen
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # optional but recommended
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }} # optional if needed for auth
        run: |
          python scripts/generate_post.py --meta-file metadata.json

      - name: Commit new content
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add content || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: add daily LeetCode post [skip ci]" || true
            git push origin HEAD:main
          fi

      - name: Build & deploy site to gh-pages
        # We use peaceiris/actions-gh-pages for deployment (works with MkDocs)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          # If you prefer deploying content/ as repo pages, adjust build step below
